MVC/Controllers/TicketMVCController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoLDS.Models;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using WebAPI.Enums;
using WebAPI.Models;

namespace MVC.Controllers
{

    public class TicketMVCController : Controller
    {
        private readonly HttpClient httpClient;
        public TicketMVCController()
        {
            httpClient = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:7235")
            };
        }

        /// <summary>
        /// Método que mosta a lista de tickets
        /// </summary>
        /// <returns>View com a lista de tickets</returns>
        public async Task<IActionResult> Index()
        {
            if (Request.Cookies.TryGetValue("UserCookie", out string cookieExists))
            {
                var cookie = System.Text.Json.JsonSerializer.Deserialize<ContaUtilizador>(cookieExists);
                string userCookieExists = cookie.Role.ToString();
                ViewBag.UserCookieExists = userCookieExists;
                ViewBag.User = cookie;
            }

            List<Ticket> tickets = await httpClient.GetFromJsonAsync<List<Ticket>>("/api/Ticket");
            return View(tickets);
        }

        /// <summary>
        /// Método que retorna a view de criação de um ticket
        /// </summary>
        /// <returns>View de criação de um ticket</returns>
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Função usada para criar um ticket na base de dados
        /// </summary>
        /// <param name="ticket">ticket a ser enviado no pedido para a base de dados</param>
        /// <returns>retorna a view da lista de tickets</returns>
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Create(Ticket ticket)
        {

            if (Request.Cookies.TryGetValue("UserCookie", out string cookieExists))
            {
                var cookie = JsonSerializer.Deserialize<ContaUtilizador>(cookieExists);
                ContaUtilizador newUser = new ContaUtilizador();
                newUser.Email = cookie.Email;
                newUser.Username = cookie.Username;
                newUser.Password = cookie.Password;
                newUser.Role = cookie.Role;
                newUser.Pontos = cookie.Pontos;

                // Obtenha o token usando o método adequado (não está claro no código fornecido)
                var tokenResponse = await httpClient.PostAsJsonAsync("api/ContaUtilizador/tokenLogged", cookie);

                if (tokenResponse.IsSuccessStatusCode)
                {
                    var tokenContent = await tokenResponse.Content.ReadAsStringAsync();

                    // Configure o token nos cabeçalhos de autorização
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenContent);

                    ticket.ContaUtilizador = newUser;

                    HttpResponseMessage response = httpClient.PostAsJsonAsync("api/Ticket", ticket).Result;

                    if (!response.IsSuccessStatusCode)
                    {
                        // Lógica para lidar com falhas na comunicação com a API
                        var statusCode = response.StatusCode;
                        ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Código de status: {statusCode}");
                        var errorContent = response.Content.ReadAsStringAsync().Result;
                        ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Detalhes: {errorContent}");
                        return BadRequest(ticket);
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    return NotFound();
                }
            }
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Método que retorna a view de edição do ticket
        /// </summary>
        /// <param name="id">Id do ticket</param>
        /// <returns>View de edição dot ticket</returns>
        public async Task<IActionResult> EditAsync(int id)
        {
            List<Ticket> tickets = await httpClient.GetFromJsonAsync<List<Ticket>>("/api/Ticket");

            Ticket ticket = null;
            if (id == null)
            {
                return BadRequest();
            }

            if (id == 0)
            {
                return NotFound();
            }

            for (int i = 0; i < tickets.Count; i++)
            {
                if (tickets[i].Id == id)
                {
                    ticket = tickets[i];
                    break;
                }
            }
            if (ticket == null)
            {
                return NotFound();
            }
            ViewBag.Ticket = ticket;

            return View(ticket);
        }

        /// <summary>
        /// Função usada para editar um ticket na base de dados
        /// </summary>
        /// <param name="ticket">ticket a ser editado</param>
        /// <returns>retorna a view da lista de tickets</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Ticket ticket)
        {
            if (Request.Cookies.TryGetValue("UserCookie", out string cookieExists))
            {
                var cookie = JsonSerializer.Deserialize<ContaUtilizador>(cookieExists);

                // Obtenha o token usando o método adequado (não está claro no código fornecido)
                var tokenResponse = await httpClient.PostAsJsonAsync("api/ContaUtilizador/tokenLogged", cookie);

                if (tokenResponse.IsSuccessStatusCode)
                {
                    var tokenContent = await tokenResponse.Content.ReadAsStringAsync();

                    // Configure o token nos cabeçalhos de autorização
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenContent);

                    if (!ModelState.IsValid)
                        return View(ticket);
                    HttpResponseMessage response = httpClient.PutAsJsonAsync($"api/Ticket/{ticket.Id}", ticket).Result;

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        var statusCode = response.StatusCode;
                        ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Código de status: {statusCode}");
                        var errorContent = response.Content.ReadAsStringAsync().Result;
                        ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Detalhes: {errorContent}");
                        return View(ticket);
                    }
                }
            }

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Método que retorna a view de delete de um ticket
        /// </summary>
        /// <param name="id">Id do ticket a eliminar</param>
        /// <returns>View de delete</returns>
        public async Task<IActionResult> DeleteAsync(int id)
        {
            if (id == null)
                return BadRequest();
            if (id == 0)
                return NotFound();
            List<Ticket> tickets = await httpClient.GetFromJsonAsync<List<Ticket>>("/api/Ticket");
            Ticket ticketEncontrado = null;
            for (int i = 0; i < tickets.Count; i++)
            {
                if (tickets[i].Id == id)
                {
                    ticketEncontrado = tickets[i];
                    break;
                }
            }
            if (ticketEncontrado == null)
                return NotFound();
            ViewBag.Ticket = ticketEncontrado;

            return View(ticketEncontrado);
        }

        /// <summary>
        /// Função usada para eliminar um ticket da base de dados
        /// </summary>
        /// <param name="name">Nome do ticket a ser eliminado</param>
        /// <returns>retorna a view da lista de tickets</returns>
        [HttpPost, ActionName("DeletePost")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteTicketAsync(int id)
        {
            if (Request.Cookies.TryGetValue("UserCookie", out string cookieExists))
            {
                var cookie = JsonSerializer.Deserialize<ContaUtilizador>(cookieExists);

                // Obtenha o token usando o método adequado (não está claro no código fornecido)
                var tokenResponse = await httpClient.PostAsJsonAsync("api/ContaUtilizador/tokenLogged", cookie);

                if (tokenResponse.IsSuccessStatusCode)
                {
                    var tokenContent = await tokenResponse.Content.ReadAsStringAsync();

                    // Configure o token nos cabeçalhos de autorização
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenContent);

                    List<Ticket> tickets = await httpClient.GetFromJsonAsync<List<Ticket>>("/api/Ticket");
                    Ticket ticketEncontrado = null;

                    for (int i = 0; i < tickets.Count; i++)
                    {
                        if (tickets[i].Id == id)
                        {
                            ticketEncontrado = tickets[i];
                            break;
                        }
                    }
                    HttpResponseMessage response = await httpClient.DeleteAsync($"/api/Ticket/{ticketEncontrado.Id}");
                    if (response.IsSuccessStatusCode)
                    {
                        // O item foi excluído com sucesso.

MVC/Views/Index.cshtml
﻿﻿@* @using WebAPI.Models*@
@model List<Ticket>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0;
        padding: 0;
        text-align: center;
    }

    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 60px;
        line-height: 60px;
        display: flex;
        justify-content: center;
        align-content: end;
    }

    h1 {
        color: #8B4513;
        font-weight: bold;
    }

    .product-container {
        display: flex;
        flex-wrap: wrap;
        gap: 29px;
    }

    .product-card {
        flex: 0 0 calc(33.33% - 20px);
        box-sizing: border-box;
        border: 1px solid #ddd;
        padding: 15px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
    }

        .product-card img {
            max-width: 100%;
            height: auto;
        }

        .product-card h3 {
            margin-top: 10px;
            color: #333;
        }

        .product-card p {
            color: #888;
        }
</style>

<h1>Tickets</h1>

<div>
    <a asp-controller="TicketMVC" asp-action="Create" class="btn btn-primary">
        Write new ticket
    </a>
</div>

@if (ViewBag.UserCookieExists == "Administrador")
{
    <div class="product-container">
        @foreach (Ticket ticket in Model)
        {
            <div class="product-card">
                <h3>@ticket.Titulo</h3>
                
                <p>Estado do ticket: @(ticket.Status)</p>

                <div>
                    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#modalTicket@ticket.Id">
                        Ler
                    </button>

                    <div class="modal fade" id="modalTicket@ticket.Id" tabindex="-1" role="dialog" aria-labelledby="modalTicketLabel@ticket.Id" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modalTicketLabel@ticket.Id">Detalhes do Ticket</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <h3>@ticket.Titulo</h3>
                                    <p>@ticket.Texto</p>
                                    <p>Estado do ticket: @(ticket.Status)</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div>
                    <form asp-controller="TicketMVC" asp-action="AlterarEstado" method="post" id="form_@ticket.Id">
                        <input type="hidden" name="ticketId" value="@ticket.Id" />
                        <input type="hidden" name="NovoEstado" id="NovoEstado_@ticket.Id" value="" />

                        <button type="button" class="btn btn-success" onclick="alterarEstado('@ticket.Id', '@ticket.Status')">
                            <span id="btnText_@ticket.Id">@((ticket.Status == WebAPI.Enums.EnumStatusTicket.Aberto) ? "Marcar como Fechado" : "Marcar como Aberto")</span>
                        </button>
                    </form>
                </div>
            </div>
        }
    </div>
}

@if (ViewBag.UserCookieExists != "Administrador")
{
    <div class="product-container">
        @foreach (Ticket ticket in Model)
        {
            @if (ViewBag.User.Id == ticket.ContaUtilizador.Id)
            {

                <div class="product-card">
                    <h3>@ticket.Titulo</h3>
                    <p>Estado do ticket: @(ticket.Status)</p>
                    <div>
                        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#modalTicket@ticket.Id">
                            Ler
                        </button>

                        <div class="modal fade" id="modalTicket@ticket.Id" tabindex="-1" role="dialog" aria-labelledby="modalTicketLabel@ticket.Id" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="modalTicketLabel@ticket.Id">Detalhes do Ticket</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <h3>@ticket.Titulo</h3>
                                        <p>@ticket.Texto</p>
                                        <p>Estado do ticket: @(ticket.Status)</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
}

<script>
    function alterarEstado(ticketId, status) {
        var novoEstado = (status === 'Aberto') ? 'Fechado' : 'Aberto';
        document.getElementById('NovoEstado_' + ticketId).value = novoEstado;
        document.getElementById('btnText_' + ticketId).innerText = 'Marcar como ' + novoEstado;

        // Submeta o formulário
        document.getElementById('form_' + ticketId).submit();
    }

</script>