MVC/Controllers/PedidoMVCController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoLDS.Models;
using System.Net.Http;
using System.Text.Json;
using WebAPI.Data;
using WebAPI.Enums;
using WebAPI.Models;

namespace MVC.Controllers
{
	public class PedidoMVCController : Controller
	{
		private readonly HttpClient httpClient;
		public PedidoMVCController()

		{
			httpClient = new HttpClient
			{
				BaseAddress = new Uri("https://localhost:7235")
			};
		}

		/// <summary>
		/// Função para mostrar pagina inicial com a listagem de pedidos
		/// </summary>
		/// <returns>A pagina web com os pedidos visiveis</returns>
		public async Task<IActionResult> Index()
		{

            if (Request.Cookies.TryGetValue("UserCookie", out string cookieExists))
            {
                var cookie = JsonSerializer.Deserialize<ContaUtilizador>(cookieExists);
                string userCookieExists = cookie.Role.ToString();
                ViewBag.UserCookieExists = userCookieExists;
                ViewBag.User = cookie;
				
				if (cookie.Role == EnumUserRole.Cliente)
				{
					List<Pedido> PedidosCliente = await httpClient.GetFromJsonAsync<List<Pedido>>($"/api/Pedidos/Cliente/{cookie.Id}");

					return View(PedidosCliente);
				}
			}

            List<Pedido> Pedidos = await httpClient.GetFromJsonAsync<List<Pedido>>("/api/Pedidos");
            return View(Pedidos);
		}

        /// <summary>
        /// Função usada para detalhar os pedidos na pagina de detalhes na web
        /// </summary>
        /// <param name="id">Id do pedido a ser detalhado</param>
        /// <returns>NotFound se não for encontrado o pedido, View com o pedido se este for encontrado</returns>
        public async Task<IActionResult> DetailsAsync(int id)
        {
            List<Pedido> pedidos = await httpClient.GetFromJsonAsync<List<Pedido>>("/api/Pedidos");

            if (id == null)
            {
                return BadRequest();
            }

            if (id.Equals(""))
            {
                return NotFound();
            }
            Pedido pedidoEncontrado = null;

            foreach (var pedido in pedidos)
            {
                if (pedido.Id == id)
                {
                    pedidoEncontrado = pedido;
                    break; // Se o menu for encontrado, podemos sair do loop.
                }
            }
            Pedido tempPedido = await httpClient.GetFromJsonAsync<Pedido>($"/api/Pedidos/{pedidoEncontrado.Id}");

            tempPedido.ContaUtilizador = pedidoEncontrado.ContaUtilizador;
            ViewBag.Pedido = tempPedido;
            if (pedidoEncontrado == null)
            {
                return NotFound();
            }
            return View(pedidoEncontrado);

        }

        /// <summary>
        /// Método que permite alterar o estado do pedido
        /// </summary>
        /// <param name="pedidoId">Id do pedido</param>
        /// <param name="NovoEstado">Novo estado para o pedido</param>
        /// <returns>retorna a view dos pedidos, ou notFound aso não encontre um pedido com esse Id</returns>
        [HttpPost]
		public async Task<IActionResult> AlterarEstado(int pedidoId, string NovoEstado)
		{
			List<Pedido> pedidos = await httpClient.GetFromJsonAsync<List<Pedido>>("/api/Pedidos");
			List<ContaUtilizador> contas = await httpClient.GetFromJsonAsync<List<ContaUtilizador>>("/api/ContaUtilizador");

			Pedido pedidoEncontrado = pedidos.FirstOrDefault(p => p.Id == pedidoId);
			ContaUtilizador contaEncontrada = contas.FirstOrDefault(t => t.Email == pedidoEncontrado.ContaUtilizador.Email);
			ContaUtilizador contaUtilizadorEncontrada = contas.FirstOrDefault(c => c.Id == contaEncontrada.Id);




			if (pedidoEncontrado != null)
			{
				if (NovoEstado.Equals("Pendente"))
				{
					pedidoEncontrado.Status = (EnumStatusPedido)0;
				}
				else if (NovoEstado.Equals("Preparar"))
				{
					pedidoEncontrado.Status = (EnumStatusPedido)1;
				}
				else if (NovoEstado.Equals("Pronto"))
				{
					pedidoEncontrado.Status = (EnumStatusPedido)2;
				}
				else if (NovoEstado.Equals("Entregue"))
				{
					pedidoEncontrado.Status = (EnumStatusPedido)3;
				}
				else if (NovoEstado.Equals("Cancelado"))
				{
					pedidoEncontrado.Status = (EnumStatusPedido)4;
				}
				HttpResponseMessage response = httpClient.PutAsJsonAsync($"api/Pedidos/{pedidoEncontrado.Id}", pedidoEncontrado).Result;
				if (!response.IsSuccessStatusCode)
				{
					// Lógica para lidar com falhas na comunicação com a API
					// Pode ser útil logar ou exibir mensagens de erro
					var statusCode = response.StatusCode;
					ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Código de status: {statusCode}");
					var errorContent = response.Content.ReadAsStringAsync().Result;
					ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Detalhes: {errorContent}");
					return BadRequest(pedidoEncontrado);
				}
				return RedirectToAction("Index");
			}
			else
			{
				return NotFound();
			}

		}

        /// <summary>
        /// Função Responsavel por apresentar apresentar a View de criação de pedido ao utilizador
        /// </summary>
        /// <returns>View de create</returns>
        public IActionResult Create()
		{
			return View();
		}

		/// <summary>
		/// Função que envia um pedido do utilizador para o WebApi
		/// </summary>
		/// <param name="pedidoViewModel">Pedido do Utilizador</param>
		/// <returns>View dos pedidos</returns>
		[ValidateAntiForgeryToken]
		[HttpPost]
		public IActionResult Create(Pedido pedidoViewModel)
		{
			if (Request.Cookies.TryGetValue("UserCookie", out string cookieExists))
			{
				var cookie = JsonSerializer.Deserialize<ContaUtilizador>(cookieExists);
				pedidoViewModel.ContaUtilizador.Email = cookie.Email;

				// Serializar o objeto pedidoViewModel para JSON e enviá-lo para a API
				HttpResponseMessage response = httpClient.PostAsJsonAsync("api/pedidos", pedidoViewModel).Result;

				// Verificar se a solicitação foi bem-sucedida
				if (response.IsSuccessStatusCode)
				{
					// Redirecionar para a página desejada após o processamento
					return RedirectToAction("Index");
				}
				else
				{
					// Lógica para lidar com falhas na comunicação com a API
					var statusCode = response.StatusCode;
					ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Código de status: {statusCode}");
					var errorContent = response.Content.ReadAsStringAsync().Result;
					ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Detalhes: {errorContent}");
					return View(pedidoViewModel);
				}
			}
			return RedirectToAction("Index");
		}

        /// <summary>
        /// Método para alterar o estado de pagamento do pedido
        /// </summary>
        /// <param name="pedidoId">Id do pedido</param>
        /// <param name="NovoEstadoPagamento">Novo estado de pagamento</param>
        /// <returns>View dos pedidos</returns>
        [HttpPost]
		public async Task<IActionResult> AlterarEstadoPagamento(int pedidoId, string NovoEstadoPagamento)
		{
			List<Pedido> pedidos = await httpClient.GetFromJsonAsync<List<Pedido>>("/api/Pedidos");
			List<ContaUtilizador> contas = await httpClient.GetFromJsonAsync<List<ContaUtilizador>>("/api/ContaUtilizador");

			Pedido pedidoEncontrado = pedidos.FirstOrDefault(p => p.Id == pedidoId);
			ContaUtilizador contaEncontrada = contas.FirstOrDefault(t => t.Email == pedidoEncontrado.ContaUtilizador.Email);
			ContaUtilizador contaUtilizadorEncontrada = contas.FirstOrDefault(c => c.Id == contaEncontrada.Id);


			if (pedidoEncontrado != null)
			{
				if (NovoEstadoPagamento.Equals("False"))
				{
					pedidoEncontrado.Pago = false;
				}
				else if (NovoEstadoPagamento.Equals("True"))
				{
					pedidoEncontrado.Pago = true;
				}
				HttpResponseMessage response = httpClient.PutAsJsonAsync($"api/Pedidos/{pedidoEncontrado.Id}", pedidoEncontrado).Result;
				if (!response.IsSuccessStatusCode)
				{
					// Lógica para lidar com falhas na comunicação com a API
					var statusCode = response.StatusCode;
					ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Código de status: {statusCode}");
					var errorContent = response.Content.ReadAsStringAsync().Result;
					ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Detalhes: {errorContent}");
					return BadRequest(pedidoEncontrado);
				}
				return RedirectToAction("Index");
			}
			else
			{
				return NotFound();
			}

		}


	}
}

MVC/Views/PedidoMVC/Create.cshtml
@using ProjetoLDS.Models
@using WebAPI.Models
@using WebAPI.Controllers
@using MVC.Models
@model Pedido
@{
	ViewData["Title"] = "Create";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
	body {
		display: flex;
		justify-content: center;
		align-items: center;
		margin: 0; /* Remove margens padrão para evitar deslocamentos */
		padding: 0; /* Certifica-se de que o padding padrão também seja removido */
		text-align: center; /* Alinha o texto no centro do corpo */
	}

	.footer {
		position: fixed;
		bottom: 0;
		width: 100%;
		height: 60px; /* Defina a altura desejada para o footer */
		line-height: 60px; /* Use o mesmo valor de altura para o line-height para centralizar verticalmente o texto */
		display: flex;
		justify-content: center;
		align-content: end;
	}

	h1 {
		color: #8B4513;
		font-weight: bold;
	}

	form {
		background-color: #fcece1; /* Adiciona fundo branco ao conteúdo */
		border: none;
	}
</style>

<h1>Create</h1>
<body>
<form method="post">
	<div class="border m-2 p-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create Menu</h2>
		</div>

		<div asp-validation-summary="All"> </div>

		<div>
			<label asp-for="ContaUtilizador.Id">Id da Conta de Utilizador</label>
			<input asp-for="ContaUtilizador.Id" class="form-control" />
			<span asp-validation-for="ContaUtilizador.Id" class="text-danger"></span>
		</div>


		<div>
			<label for="quantidadeItemsPedido">Número de ItemsPedido:</label>
			<input type="number" id="quantidadeItemsPedido" class="form-control" />
		</div>

		<div id="itemsPedidoContainer"></div>
			<button type="button" id="adicionarItemsPedido" class="btn btn-primary" style="border-color:transparent">Adicionar ItemsPedido</button>

		<div>
			<div id="dynamicItemsPedido">
				<!-- Campos dinâmicos serão adicionados aqui -->
			</div>
		</div>

			<button type="submit" class="btn btn-primary" style="border-color:transparent">Create</button>

			<a asp-controller="PedidoMVC" asp-action="Index" class="btn btn-secondary" style="color:#8b4513">Back</a>
	</div>
</form>
</body>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}

	<script>
		$(document).ready(function () {
			$("#adicionarItemsPedido").click(function () {
				var quantidadeItemsPedido = $("#quantidadeItemsPedido").val();

				// Limpar campos dinâmicos existentes
				$("#dynamicItemsPedido").empty();

				// Adicionar campos dinâmicos com base na quantidade especificada
				for (var i = 0; i < quantidadeItemsPedido; i++) {
					var dynamicField = $("<div>")
						.append($("<h4>").addClass("text-primary").text("Item"))
						.append(
							$("<label>").attr("for", `ItensPedido_${i}__ItemCompra_Name`).text(`Nome do Item ${i + 1}:`),
							$("<input>")
								.attr({
									type: "text",
									id: `ItensPedido_${i}__ItemCompra_Name`,
									name: `ItensPedido[${i}].ItemCompra.Name`,
									class: "form-control"
								}),
							$("<span>").attr("asp-validation-for", `ItensPedido[${i}].ItemCompra.Name`).addClass("text-danger")
						)
						.append(
							$("<div>").append(
								$("<label>").attr("for", `quantidadeItemsModificar_${i}`).text("Quantidade de Itens a Modificar:"),
								$("<input>")
									.attr({
										type: "number",
										id: `quantidadeItemsModificar_${i}`,
										name: `QuantidadeItemsModificar[${i}]`,
										class: "form-control"
									})
							)
						)
						.append($("<div>").attr("id", "itemsPedidoContainer"))
						.append(
							$("<button>")
								.attr({ type: "button", class: "btn btn-primary adicionarItemsModificar" })
								.text("Adicionar Modificações")
						)
						.append(
							$("<div>").addClass("dynamicItemsModificar").append(
								// Campos dinâmicos serão adicionados aqui
							)
						);

					$("#dynamicItemsPedido").append(dynamicField);
				}
			});

			// Evento para adicionar itens modificados
			$("#dynamicItemsPedido").on("click", ".adicionarItemsModificar", function () {
				var container = $(this).closest("div");
				var index = container.index();
				var quantidadeItemsPedido = $("#quantidadeItemsModificar_" + index).val();

				// Limpar campos dinâmicos existentes apenas dentro do contêiner pai
				container.find(".dynamicItemsModificar").empty();

				// Adicionar campos dinâmicos com base na quantidade especificada
				for (var i = 0; i < quantidadeItemsPedido; i++) {
					var dynamicField = $("<div>")
						.append(
							$("<label>").attr("for", `ItensPedido_${index}__EditIngredientes_${i}__Item_Name`).text(`Item Modificar ${i + 1}:`),
							$("<input>")
								.attr({
									type: "text",
									id: `ItensPedido_${index}__EditIngredientes_${i}__Item_Name`,
									name: `ItensPedido[${index}].EditIngredientes[${i}].Item.Name`,
									class: "form-control"
								}),
							$("<span>").attr("asp-validation-for", `ItensPedido[${index}].EditIngredientes[${i}].Item.Name`).addClass("text-danger")
						)
						.append(
							$("<label>").attr("for", `ItensPedido_${index}__EditIngredientes_${i}__Ingrediente_Name`).text(`Ingrediente a Modificar ${i + 1}:`),
							$("<input>")
								.attr({
									type: "text",
									id: `ItensPedido_${index}__EditIngredientes_${i}__Ingrediente_Name`,
									name: `ItensPedido[${index}].EditIngredientes[${i}].Ingrediente.Name`,
									class: "form-control"
								}),
							$("<span>").attr("asp-validation-for", `ItensPedido[${index}].EditIngredientes[${i}].Ingrediente.Name`).addClass("text-danger")
						)
						.append(
							$("<label>").attr("for", `ItensPedido_${index}__EditIngredientes_${i}__Active`).text(`Activo ${i + 1}:`),
							$("<input>")
								.attr({
									type: "checkbox",
									id: `ItensPedido_${index}__EditIngredientes_${i}__Active`,
									name: `ItensPedido[${index}].EditIngredientes[${i}].Active`,
									class: "form-check-input"
								})
								// Adicione um evento change para converter o valor para booleano
								.on("change", function () {
									// Atualize o valor do atributo 'value' para ser 'true' ou 'false'
									$(this).val(this.checked.toString());
								}),
							$("<span>").attr("asp-validation-for", `ItensPedido[${index}].EditIngredientes[${i}].Active`).addClass("text-danger")
						);

					container.find(".dynamicItemsModificar").append(dynamicField);
				}
			});
		});
	</script>


}

MVC/Views/PedidoMVC/Details.cshtml
@model WebAPI.Models.Pedido
@using ProjetoLDS.Models
@{
	ViewData["Title"] = "Details";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
	body {
		display: flex;
		justify-content: center;
		align-items: center;
		margin: 0;
		padding: 0;
		text-align: center;
	}

	.footer {
		position: fixed;
		bottom: 0;
		width: 100%;
		height: 60px;
		line-height: 60px;
		display: flex;
		justify-content: center;
		align-content: end;
	}

	h1 {
		color: #8B4513;
		font-weight: bold;
	}

	form {
		background-color: #fcece1;
		border: none;
	}

	.tbody tr:first-child {
		background-color: #ffad73;
	}

	.tbody tr:not(:first-child) {
		background-color: #ffd5b8;
	}
</style>

<h1>Detalhes do pedido</h1>
<body>
	<h2>Itens do Pedido</h2>
	<table class="table">
		<thead>
			<tr>
				<th>ID do Item Pedido</th>
				<th>Nome do Produto</th>
				<th>Preço</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var itemPedido in ViewBag.Pedido.ItensPedido)
			{
				<tr>
					<td>@itemPedido.Id</td>
					<td>

						@itemPedido.ItemCompra.Name

					</td>
					<td>

						@(itemPedido.Preco / 100M)€

					</td>
				</tr>

				@foreach (var editIngrediente in itemPedido.EditIngredientes)
				{
					<tr>
						<td><strong>Ingrediente Editado</strong></td>
						<td>@editIngrediente.Item.Name</td>
						<td>0.00€</td>
						<td>@editIngrediente.Ingrediente.Name</td>
						@if (editIngrediente.Active)
						{
							<td>Adicionar</td>
						}
						else
						{
							<td>Remover</td>
						}
					</tr>
				}
			}
		</tbody>
	</table>
	<a asp-controller="PedidoMVC" asp-action="Index" class="btn btn-secondary" style="color:#8b4513">Back</a>
</body>

MVC/Views/PedidoMVC/Index.cshtml
@model List<Pedido>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0;
        padding: 0;
        text-align: center;
    }

    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 60px;
        line-height: 60px;
        display: flex;
        justify-content: center;
        align-content: end;
    }

    h1 {
        color: #8B4513;
        font-weight: bold;
    }

    .product-container {
        display: flex;
        flex-wrap: wrap;
        gap: 29px;
        justify-content: center;
    }

    .product-card {
        flex: 0 0 calc(33.33% - 20px);
        box-sizing: border-box;
        border: 1px solid #ddd;
        padding: 15px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
    }

        .product-card h3 {
            margin-top: 10px;
            color: #333;
        }

        .product-card p {
            color: #888;
        }
</style>

<h1>Pedidos</h1>

@if (ViewBag.UserCookieExists != "Cliente")
{
    <div class="product-container">

        @foreach (Pedido pedido in Model)
        {
            <div class="product-card">
                <h3>Número de identificação: @pedido.Id</h3>
                <p>Estado do pedido: @pedido.Status</p>
                <p>Estado de pagamento: @(pedido.Pago ? "Pago" : "Não pago")</p>


                <div>
                    <a asp-controller="PedidoMVC" asp-action="Details" asp-route-id="@pedido.Id" class="btn btn-primary">Ver Detalhes</a>
                </div>
                @if (ViewBag.UserCookieExists == "Administrador")
                {
                    <div>
                        <form asp-controller="PedidoMVC" asp-action="AlterarEstadoPagamento" method="post" id="form_@pedido.Id">
                            <input type="hidden" name="pedidoId" value="@pedido.Id" />
                            <input type="hidden" name="NovoEstadoPagamento" id="NovoEstado_@pedido.Id" value="" />


                            <button type="button" class="btn btn-success" onclick="alterarEstado('@pedido.Id', '@pedido.Pago')">
                                <span id="btnText_@pedido.Id">@((pedido.Pago == false) ? "Marcar como pago" : "Marcar como não pago")</span>
                            </button>

                        </form>
                    </div>
                }

                @if (ViewBag.UserCookieExists == "Administrador")
                {
                    <div>
                        <form asp-controller="PedidoMVC" asp-action="AlterarEstado" method="post">
                            <input type="hidden" name="pedidoId" value="@pedido.Id" />
                            <select name="NovoEstado" class="form-control" onchange="habilitarBotao(this)">
                                <option value="" selected disabled hidden>Altere o estado do pedido</option>
                                @if (!pedido.Pago)
                                {
                                    <option value="Pendente">Pendente</option>
                                    <option value="Cancelado">Cancelado</option>
                                }
                                else
                                {
                                    <option value="Preparar">A preparar</option>
                                    <option value="Pronto">Pronto</option>
                                    <option value="Entregue">Entregue</option>
                                }
                            </select>

                            <button type="submit" class="btn btn-success" disabled>Alterar</button>
                        </form>
                    </div>
                }
            </div>
        }
    </div>
}

@if (ViewBag.UserCookieExists == "Cliente")
{
    <div class="product-container">

        @foreach (Pedido pedido in Model)
        {
@*             @if (ViewBag.User.Id == pedido.ContaUtilizador.Id)
            { *@
                <div class="product-card">
                    <h3>Número de identificação: @pedido.Id</h3>
                <p>Estado do pedido: @pedido.Status</p>
                <p>Estado de pagamento: @(pedido.Pago ? "Pago" : "Não pago")</p>


                <div>
                    <a asp-controller="PedidoMVC" asp-action="Details" asp-route-id="@pedido.Id" class="btn btn-primary">Ver Detalhes</a>
                </div>
                
                </div>
            @* } *@
        }
    </div>
}

<script>
    function habilitarBotao(selectElement) {
        var alterarButton = selectElement.parentNode.querySelector('button[type="submit"]');
        if (selectElement.value !== "") {
            alterarButton.removeAttribute('disabled');
        } else {
            alterarButton.setAttribute('disabled', 'disabled');
        }
    }

    function alterarEstado(pedidoId, Pago) {
        var novoEstadoPagamento = (Pago === 'True') ? 'False' : 'True';
        document.getElementById('NovoEstado_' + pedidoId).value = novoEstadoPagamento;
        document.getElementById('btnText_' + pedidoId).innerText = 'Marcar como ' + ((novoEstadoPagamento === 'True') ? 'não pago' : 'pago');

        // Submeta o formulário
        document.getElementById('form_' + pedidoId).submit();
    }
</script>