MVC/Controllers/ItemsMVCController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using ProjetoLDS.Models;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using WebAPI.Data;
using WebAPI.Models;

namespace MVC.Controllers
{
    public class ItemsMVCController : Controller
    {
        private readonly HttpClient httpClient;
        public ItemsMVCController()
        {
            // Configurar o HttpClient para fazer chamadas à sua Web API
            httpClient = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:7235") // Defina sua URL da Web API aqui
            };
        }
        /// <summary>
        /// Função para mostrar os items na web
        /// </summary>
        /// <returns>view com a lista dos items</returns>
        public async Task<IActionResult> Index()
        {
            if (Request.Cookies.TryGetValue("UserCookie", out string cookieExists))
            {
                var cookie = System.Text.Json.JsonSerializer.Deserialize<ContaUtilizador>(cookieExists);
                string userCookieExists = cookie.Role.ToString();
                ViewBag.UserCookieExists = userCookieExists;
            }


            List<Item> items = await httpClient.GetFromJsonAsync<List<Item>>("/api/Items");

            return View(items);
        }

        /// <summary>
        /// Método que retorna a view do create
        /// </summary>
        /// <returns>View do create</returns>
        public async Task<IActionResult> CreateAsync()
        {
            List<Ingrediente> ingredientes = await httpClient.GetFromJsonAsync<List<Ingrediente>>("/api/Stock");

            Item item = new Item();
            item.Ingredientes = ingredientes.ToList();
            ViewBag.Item = item;
            return View();
        }

        /// <summary>
        /// Função que envia um item do utilizador para o WebApi
        /// </summary>
        /// <param name="itemViewModel">Item do Utilizador</param>
        /// <returns>Lista de items, caso o novo seja adicionado, ou o formulário caso algum problema tenha surgido</returns>
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> CreateAsync(Item item, int[] ingredientesSelecionados)
        {

            if (ingredientesSelecionados == null || ingredientesSelecionados.Length == 0)
            {
                return RedirectToAction("Index");
            }
            if (Request.Cookies.TryGetValue("UserCookie", out string cookieExists))
            {
                var cookie = System.Text.Json.JsonSerializer.Deserialize<ContaUtilizador>(cookieExists);

                // Obtenha o token usando o método adequado (não está claro no código fornecido)
                var tokenResponse = await httpClient.PostAsJsonAsync("api/ContaUtilizador/tokenLogged", cookie);
                if (tokenResponse.IsSuccessStatusCode)
                {
                    var tokenContent = await tokenResponse.Content.ReadAsStringAsync();
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenContent);
                    // Configure o token nos cabeçalhos de autorização
                    if (item.Image != null)
                    {
                        // Salvar o arquivo no sistema de arquivos do servidor
                        item.ImagePath = SaveImage(item.Image);
                    }
                    item.Image = null;

                    // Serializar o objeto itemViewModel para JSON e enviá-lo para a API
                    HttpResponseMessage response = httpClient.PostAsJsonAsync("api/items", item).Result;
                    Item createdItem = await response.Content.ReadFromJsonAsync<Item>();


                    foreach (var ing in ingredientesSelecionados)
                    {
                        HttpResponseMessage response2 = httpClient.GetAsync($"api/Stock/{ing}").Result;

                        if (response.IsSuccessStatusCode)
                        {
                            // Deserializar o Ingrediente
                            string content = await response2.Content.ReadAsStringAsync();
                            Ingrediente ingrediente = JsonConvert.DeserializeObject<Ingrediente>(content);

                            // Comparar o TypeComida com null
                            if (ingrediente.TypeComida == item.TypeComida)
                            {
                                IngredienteAtribuido ingredienteAtribuido = new IngredienteAtribuido();
                                ingredienteAtribuido.ItemName = createdItem.Name;
                                ingredienteAtribuido.IdIngrediente = ing;
                                ingredienteAtribuido.ItemId = createdItem.Id;

                                HttpResponseMessage response1 = httpClient.PostAsJsonAsync("api/IngredienteAtribuido", ingredienteAtribuido).Result;

                                // Aqui você pode adicionar mais lógica, se necessário
                            }
                        }
                        else
                        {
                            var statusCode = response2.StatusCode;
                            ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Código de status: {statusCode}");
                            var errorContent = response2.Content.ReadAsStringAsync().Result;
                            ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Detalhes: {errorContent}");
                            return View(item);
                        }
                    }

                    // Verificar se a solicitação foi bem-sucedida
                    if (response.IsSuccessStatusCode)
                    {
                        // Redirecionar para a página desejada após o processamento
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        // Lógica para lidar com falhas na comunicação com a API
                        // Pode ser útil logar ou exibir mensagens de erro
                        var statusCode = response.StatusCode;
                        ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Código de status: {statusCode}");
                        var errorContent = response.Content.ReadAsStringAsync().Result;
                        ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Detalhes: {errorContent}");
                        return View(item);
                    }
                }
            }
            return RedirectToAction("Index");

        }

        /// <summary>
        /// Função usada para guardar a imagem do Item
        /// </summary>
        /// <param name="imageFile">Imagem a ser guardada</param>
        /// <returns>Path da imagem</returns>
        private string SaveImage(IFormFile imageFile)
        {
            string uploadsFolder = Path.Combine("wwwroot", "Images", "ItemImages");

            if (!Directory.Exists(uploadsFolder))
            {
                Directory.CreateDirectory(uploadsFolder);
            }

            string uniqueFileName = Guid.NewGuid().ToString() + "_" + imageFile.FileName;

            string filePath = Path.Combine(uploadsFolder, uniqueFileName);

            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                imageFile.CopyTo(fileStream);
            }

            return uniqueFileName;
        }

        /// <summary>
        /// Método que retorna a view do edit
        /// </summary>
        /// <param name="id">Id do item a editar</param>
        /// <returns>view do edit</returns>
        public async Task<IActionResult> EditAsync(int? id)
        {
            List<Item> items = await httpClient.GetFromJsonAsync<List<Item>>("/api/Items");
            List<Ingrediente> ingredientes = await httpClient.GetFromJsonAsync<List<Ingrediente>>("/api/Stock");
            List<IngredienteAtribuido> ingredientesAtribuidos = await httpClient.GetFromJsonAsync<List<IngredienteAtribuido>>("/api/IngredienteAtribuido");
            if (id == null)
            {
                return BadRequest();
            }

			if (id.Equals(""))
            {
                return NotFound();
            }
            Item itemEncontrado = null;

            for (int i = 0; i < items.Count; i++)
            {
                if (items[i].Id == id)
                {
                    itemEncontrado = items[i];
                    break; // Se o item for encontrado, podemos sair do loop.
                }
            }

            itemEncontrado.Ingredientes = ingredientes.ToList();
            ViewBag.Item = itemEncontrado;
            ViewBag.IngredientesAtribuido = ingredientesAtribuidos.Where(ia => ia.ItemId == itemEncontrado.Id).ToList();

            if (itemEncontrado == null)
            {
                return NotFound();
            }
            return View(itemEncontrado);
        }

        /// <summary>
        /// Método que envia um item e seus ingredientes para a WebAPI para estes serem editados
        /// </summary>
        /// <param name="item">item a editar</param>
        /// <param name="ingredientesSelecionados">ingredientes selecionados do mesmo ingrediente</param>
        /// <returns>View do menu de items</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Item item, int[] ingredientesSelecionados)
        {
			if (ingredientesSelecionados == null || ingredientesSelecionados.Length == 0)
			{
				return RedirectToAction("Index");
			}
			
            if (Request.Cookies.TryGetValue("UserCookie", out string cookieExists))
            {

MVC/Views/ItemsMVC/Create.cshtml
@model Item
@using WebAPI.Enums;

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0; 
        padding: 0; 
        text-align: center; 
    }
    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 60px; 
        line-height: 60px; 
        display: flex;
        justify-content: center;
        align-content: end;
    }

    h2 {
        color: #8B4513;
        font-weight: bold;
    }

    form {
        background-color: #fcece1; 
        border: none;
    }
</style>
<body>
    <form method="post" enctype="multipart/form-data">
    <div class="border m-2 p-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Item</h2>
        </div>
        <div asp-validation-summary="All"> </div>
            <input asp-for="Id" hidden />

        <div class="mb-3">
            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control" required />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Preco" class="form-label"></label>
                    <input asp-for="Preco" class="form-control" required />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Image" class="form-label"></label>
                <input asp-for="Image" type="file" class="form-control" required/>
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="mb-3">
                @Html.DropDownListFor(m => m.TypeComida,
                new SelectList(Enum.GetValues(typeof(EnumTypeComida))),
                new { @class = "form-input" })
            </div>
            <label>Ingredientes de hamburguer</label>
            <div>
                @{

                }


                @foreach (var ingrediente in ViewBag.Item.Ingredientes)
                {
                    @if (ingrediente.TypeComida == (EnumTypeComida)0){
                    <div class="form-check">
                            <input type="checkbox" id="Check_@ingrediente.Id" name="ingredientesSelecionados" value="@ingrediente.Id" />
                            <label for="Check_@ingrediente.Id">@ingrediente.Name</label>
                    </div>
                        }
                }
            </div>
                <label>Ingredientes de bebida</label>
                <div>
                    @{

                    }

                    @foreach (var ingrediente in ViewBag.Item.Ingredientes)
                    {
                        @if (ingrediente.TypeComida == (EnumTypeComida)1)
                        {
                            <div class="form-check">
                                <input type="checkbox" id="Check_@ingrediente.Id" name="ingredientesSelecionados" value="@ingrediente.Id" />
                                <label for="Check_@ingrediente.Id">@ingrediente.Name</label>
                            </div>
                        }
                    }
                </div>
                <label>Ingredientes de batata</label>
                <div>
                    @{

                    }

                    @foreach (var ingrediente in ViewBag.Item.Ingredientes)
                    {
                        @if (ingrediente.TypeComida == (EnumTypeComida)2)
                        {
                            <div class="form-check">
                                <input type="checkbox" id="Check_@ingrediente.Id" name="ingredientesSelecionados" value="@ingrediente.Id" />
                                <label for="Check_@ingrediente.Id">@ingrediente.Name</label>
                            </div>
                        }
                    }
                </div>
        </div>
            <button type="submit" class="btn btn-primary" style="border-color:transparent">Create</button>
            <a asp-controller="ItemsMVC" asp-action="Index" class="btn btn-secondary" style="color:#8b4513">Back</a>
    </div>
</form>
</body>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

MVC/Views/ItemsMVC/Delete.cshtml
@model Item
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0;
        padding: 0; 
        text-align: center; 
    }
    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 60px;
        line-height: 60px; 
        display: flex;
        justify-content: center;
        align-content: end;
    }

    h2{
        color: #8B4513;
        font-weight: bold;
    }

    form {
        background-color: #fcece1; /* Adiciona fundo branco ao conteúdo */
        border: none;
    }
</style>


<h1>Delete Item</h1>
<body>
    <form method="post" asp-action="DeleteConfirmed">
    <input asp-for="Name" hidden />
    <div class="border m-2 p-4">
        <div asp-validation-summary="All"></div>
            @if (TempData["ErrorMessage"] != null)
            {
                <div class="alert alert-danger" role="alert">
                    @TempData["ErrorMessage"]
                </div>
            }
        <div class="mb-3">
            <label asp-for="Name" class="form-label"></label>
            <input asp-for="Name" class="form-control" disabled />
        </div>
            <input asp-for="Id" hidden />
            <input asp-for="ImagePath" hidden />
            <button type="submit" class="btn btn-primary" style="border-color:transparent">Delete</button>
            <a asp-controller="ItemsMVC" asp-action="Index" class="btn btn-secondary" style="color:#8b4513">Back</a>
    </div>
</form>
</body>

MVC/Views/ItemsMVC/Edit.cshtml
@model Item
@using WebAPI.Enums;

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0; 
        padding: 0;
        text-align: center; 
    }
    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 60px;
        line-height: 60px; 
        display: flex;
        justify-content: center;
        align-content: end;
    }

    h1 {
        color: #8B4513;
        font-weight: bold;
    }

    form {
        background-color: #fcece1; 
        border: none;
    }
</style>


<h1>Edit Item</h1>
<body>
    <form method="post" asp-controller="ItemsMVC" asp-action="Edit" enctype="multipart/form-data">
    <div class="border m-2 p-4">
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
                <input asp-for="Id" hidden />
                <input asp-for="ImagePath" hidden />
            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" required/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Preco" class="form-label"></label>
                <input asp-for="Preco" class="form-control" required/>
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Image" class="form-label"></label>
                <input asp-for="Image" type="file" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="mb-3">
                @Html.DropDownListFor(m => m.TypeComida,
                new SelectList(Enum.GetValues(typeof(EnumTypeComida))))
            </div>
            <label>Ingredientes</label>
            <div>
                @{

                }
                @foreach (var ingrediente in ViewBag.Item.Ingredientes)
                {
                        @if (@ingrediente.TypeComida == Model.TypeComida){
                            bool isChecked = false;
                            foreach (var ingredienteAtribuido in ViewBag.IngredientesAtribuido)
                            {
                                if (ingredienteAtribuido.IdIngrediente == ingrediente.Id)
                                {
                                    isChecked = true;
                                    break;
                                }
                            }
                            <div class="form-check">
                                <input type="checkbox" id="Check_@ingrediente.Id" name="ingredientesSelecionados" value="@ingrediente.Id" checked="@isChecked"/>
                                <label for="Check_@ingrediente.Id">@ingrediente.Name</label>
                            </div>
                        }
                    }
            </div>
                <button type="submit" class="btn btn-primary" style="border-color:transparent">Update</button>
                <a asp-controller="ItemsMVC" asp-action="Index" class="btn btn-secondary" style="color:#8b4513">Back</a>
        </div>
    </form>
</body>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

MVC/Views/ItemsMVC/Index.cshtml
@model List<Item>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 60px; 
        line-height: 60px;
        / Use o mesmo valor de altura para o line-height para centralizar verticalmente o texto / display: flex;
        justify-content: center;
        align-content: end;
        padding-left: 550px;
    }

    h1 {
        color: #8B4513;
        font-weight: bold;
    }

    .product-container {
        display: flex;
        flex-wrap: wrap; 
        gap: 29px;
    }

    .product-card {
        flex: 0 0 calc(33.33% - 20px); 
        box-sizing: border-box; 
        border: 1px solid #ddd;
        padding: 15px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px; 
    }


        .product-card img {
            max-width: 100%;
            height: auto;
        }

        .product-card h3 {
            margin-top: 10px;
            color: #333;
        }

        .product-card p {
            color: #888;
        }
</style>

<h1>Items</h1>

@if (ViewBag.UserCookieExists == "Administrador")
{
    <div>
        <a asp-controller="ItemsMVC" asp-action="Create" class="btn btn-primary">
            Create New Item
        </a>
    </div>
}

<div class="product-container">
    @foreach (Item item in Model)
    {
        <div class="product-card">
            <!-- Adicione a imagem do item aqui -->
            <img src="~/Images/ItemImages/@item.ImagePath" alt="Imagem do Item" style="width: 200px; height: 200px; object-fit: cover; display: block; margin: 0 auto;">

            <h3>@item.Name</h3>
            <p>@(item.Preco / 100M)€</p>

            @if (ViewBag.UserCookieExists == "Administrador")
            {
                <div>
                    <a asp-controller="ItemsMVC" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    <a asp-controller="ItemsMVC" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </div>
            }
        </div>
    }
</div>