MVC/Controllers/MenuMVCController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoLDS.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using WebAPI.Data;
using WebAPI.Models;

namespace MVC.Controllers
{
    public class MenuMVCController : Controller
    {
        private readonly HttpClient httpClient;
        public MenuMVCController()

        {
            httpClient = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:7235") // Defina sua URL da Web API aqui
            };
        }

        /// <summary>
        /// Função para mostrar pagina inicial com a listagem de menus
        /// </summary>
        /// <returns>A pagina web com os menus visiveis</returns>
        public async Task<IActionResult> Index()
        {
            if (Request.Cookies.TryGetValue("UserCookie", out string cookieExists))
            {
                var cookie = System.Text.Json.JsonSerializer.Deserialize<ContaUtilizador>(cookieExists);
                string userCookieExists = cookie.Role.ToString();
                ViewBag.UserCookieExists = userCookieExists;
            }

            List<Menu> menus = await httpClient.GetFromJsonAsync<List<Menu>>("/api/Menu");
            return View(menus);
        }

        /// <summary>
        /// Método que devolve a view de criação de um menu
        /// </summary>
        /// <returns>View de criação de um menu</returns>
        public async Task<IActionResult> CreateAsync()
        {
            List<Item> items = await httpClient.GetFromJsonAsync<List<Item>>("/api/Items");


            Menu menu = new Menu();
            menu.Items = items.ToList();
            ViewBag.Menu = menu;
            return View(menu);
        }

        //// <summary>
        /// Função que envia um item do utilizador para o WebApi
        /// </summary>
        /// <param name="itemViewModel">Item do Utilizador</param>
        /// <returns></returns>
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> CreateAsync(Menu menu, int[] itemsSelecionados)
        {
			if (itemsSelecionados == null || itemsSelecionados.Length == 0)
			{
				return RedirectToAction("Index");
			}
			if (Request.Cookies.TryGetValue("UserCookie", out string cookieExists))
            {
                var cookie = JsonSerializer.Deserialize<ContaUtilizador>(cookieExists);

                // Obtenha o token usando o método adequado (não está claro no código fornecido)
                var tokenResponse = await httpClient.PostAsJsonAsync("api/ContaUtilizador/tokenLogged", cookie);

                if (tokenResponse.IsSuccessStatusCode)
                {
                    var tokenContent = await tokenResponse.Content.ReadAsStringAsync();

                    // Configure o token nos cabeçalhos de autorização
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenContent);

                    List<Item> items = await httpClient.GetFromJsonAsync<List<Item>>("/api/Items");

                    if (menu.Image != null)
                    {
                        // Salvar o arquivo no sistema de arquivos do servidor
                        menu.ImagePath = SaveImage(menu.Image);
                    }
                    menu.Image = null;


                    // Serializar o objeto itemViewModel para JSON e enviá-lo para a API
                    HttpResponseMessage response = httpClient.PostAsJsonAsync("api/Menu", menu).Result;
                    Menu createdMenu = await response.Content.ReadFromJsonAsync<Menu>();

                    foreach (var item in itemsSelecionados)
                    {
                        ItemAtribuido itemAtribuido = new ItemAtribuido();
                        itemAtribuido.MenuName = createdMenu.Name;
                        itemAtribuido.IdItem = item;
                        itemAtribuido.MenuId = createdMenu.Id;
                        HttpResponseMessage response1 = httpClient.PostAsJsonAsync($"api/ItemAtribuido", itemAtribuido).Result;
                    }

                    if (!response.IsSuccessStatusCode)
                    {
                        // Lógica para lidar com falhas na comunicação com a API
                        // Pode ser útil logar ou exibir mensagens de erro
                        var statusCode = response.StatusCode;
                        ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Código de status: {statusCode}");
                        var errorContent = response.Content.ReadAsStringAsync().Result;
                        ModelState.AddModelError(string.Empty, $"Erro na comunicação com a API. Detalhes: {errorContent}");
                        return View(menu);
                    }
                }
            }

            return RedirectToAction("Index");
        }


        /// <summary>
        /// Função usada para guardar a imagem do Menu
        /// </summary>
        /// <param name="imageFile">Imagem a ser guardada</param>
        /// <returns>Path da imagem</returns>
        private string SaveImage(IFormFile imageFile)
        {
            string uploadsFolder = Path.Combine("wwwroot", "Images", "ItemImages");

            if (!Directory.Exists(uploadsFolder))
            {
                Directory.CreateDirectory(uploadsFolder);
            }

            string uniqueFileName = Guid.NewGuid().ToString() + "_" + imageFile.FileName;

            string filePath = Path.Combine(uploadsFolder, uniqueFileName);

            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                imageFile.CopyTo(fileStream);
            }

            return uniqueFileName;
        }



        /// <summary>
        /// Função usada para detalhar os menus na pagina de detalhes na web
        /// </summary>
        /// <param name="id">nome do menu a ser detalhado</param>
        /// <returns>NotFound se não for encontrado o menu, View com o menu se este for encontrado</returns>
        [HttpGet]
        public async Task<IActionResult> Details(int Id)
        {
            {
                if (Request.Cookies.TryGetValue("UserCookie", out string cookieExists))
                {
                    var cookie = JsonSerializer.Deserialize<ContaUtilizador>(cookieExists);

                    // Obtenha o token usando o método adequado (não está claro no código fornecido)
                    var tokenResponse = await httpClient.PostAsJsonAsync("api/ContaUtilizador/tokenLogged", cookie);

                    if (tokenResponse.IsSuccessStatusCode)
                    {
                        var tokenContent = await tokenResponse.Content.ReadAsStringAsync();

                        // Configure o token nos cabeçalhos de autorização
                        httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenContent);

                        List<Menu> menus = await httpClient.GetFromJsonAsync<List<Menu>>("/api/Menu");
                        List<Item> items = await httpClient.GetFromJsonAsync<List<Item>>("/api/Items");
                        List<ItemAtribuido> itemsAtribuidos = await httpClient.GetFromJsonAsync<List<ItemAtribuido>>("/api/ItemAtribuido");

                        if (Id == null)
                        {
                            return BadRequest();
                        }

                        if (Id.Equals(""))
                        {
                            return NotFound();
                        }
                        Menu menuEncontrado = null;

                        for (int i = 0; i < menus.Count; i++)
                        {
                            if (menus[i].Id == Id)
                            {
                                menuEncontrado = menus[i];
                                break; 
                            }
                        }

                        if (menuEncontrado == null)
                        {
                            return NotFound(); // Menu não encontrado
                        }

                        var itemsDoMenu = itemsAtribuidos.Where(ia => ia.MenuId == menuEncontrado.Id).ToList();

                        List<Item> itemsVB = new List<Item>();

                        foreach (var item in itemsDoMenu)
                        {
                            Item itemToInsert = items.Find(items => items.Id == item.IdItem);
                            itemsVB.Add(itemToInsert);
                        }

                        ViewBag.ItemAtribuido = itemsVB;

                        return View(menuEncontrado);


                    }
                }

                return RedirectToAction("Index");
            }
        }

        /// <summary>
        /// Método que mostra a view do edit
        /// </summary>
        /// <param name="id">id do meu a editar</param>
        /// <returns>View do edit</returns>
        public async Task<IActionResult> EditAsync(int? id)
        {
            List<Menu> menus = await httpClient.GetFromJsonAsync<List<Menu>>("/api/Menu");
            List<Item> items = await httpClient.GetFromJsonAsync<List<Item>>("/api/Items");
            List<ItemAtribuido> itemsAtribuidos = await httpClient.GetFromJsonAsync<List<ItemAtribuido>>("/api/ItemAtribuido");
            if (id == null)
            {
                return BadRequest();
            }

            if (id.Equals(""))
            {
                return NotFound();
            }
            Menu menuEncontrado = null;

            for (int i = 0; i < menus.Count; i++)
            {
                if (menus[i].Id == id)
                {
                    menuEncontrado = menus[i];
                    break; // Se o menu for encontrado, podemos sair do loop.
                }
            }
            menuEncontrado.Items = items.ToList();

MVC/Views/MenuMVC/Create.cshtml
@model Menu
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0; 
        padding: 0; 
        text-align: center; 
    }

    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 60px; 
        line-height: 60px;
        display: flex;
        justify-content: center;
        align-content: end;
    }

    h2 {
        color: #8B4513;
        font-weight: bold;
    }

    form {
        background-color: #fcece1; 
        border: none;
    }
</style>
<body>
    <form method="post" enctype="multipart/form-data">
        <div class="border m-2 p-4">
            <div class="row pb-2">
                <h2 class="text-primary">Create Menu</h2>
            </div>
            <div asp-validation-summary="All"> </div>
            <input asp-for="Id" hidden />

            <div class="mb-3">
                <div class="mb-3">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control" required />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Preco" class="form-label"></label>
                    <input asp-for="Preco" class="form-control" />
                    <span asp-validation-for="Preco" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="PontosNecessarios" class="form-label"></label>
                    <input asp-for="PontosNecessarios" class="form-control" />
                    <span asp-validation-for="PontosNecessarios" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Image" class="form-label"></label>
                    <input asp-for="Image" type="file" class="form-control" required />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <label>Items</label>
                <div>
                    @{

                    }
                    @foreach (var item in ViewBag.Menu.Items)
                    {
                        <div class="form-check">
                            <input type="checkbox" id="Check_@item.Id" name="itemsSelecionados" value="@item.Id" />
                            <label for="Check_@item.Id">@item.Name</label>
                        </div>
                    }
                </div>
            </div>
            <button type="submit" class="btn btn-primary" style="border-color:transparent">Create</button>
            <a asp-controller="MenuMVC" asp-action="Index" class="btn btn-secondary" style="color:#8b4513">Back</a>
        </div>
    </form>
</body>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

MVC/Views/MenuMVC/Delete.cshtml
@model Menu
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0;
        padding: 0; 
        text-align: center; 
    }

    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 60px; 
        line-height: 60px; 
        display: flex;
        justify-content: center;
        align-content: end;
    }

    h2 {
        color: #8B4513;
        font-weight: bold;
    }

    form {
        background-color: #fcece1; 
        border: none;
    }
</style>


<h1>Delete Menu</h1>
<body>
    <form method="post" asp-action="DeleteConfirmed">
        <input asp-for="Name" hidden />
        <div class="border m-2 p-4">
            <div class="row pb-2">
                <h2 class="text-primary">Delete Menu</h2>
            </div>
            <div asp-validation-summary="All"></div>
            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" disabled />
            </div>
            <input asp-for="Id" hidden />
            <input asp-for="ImagePath" hidden />
            <button type="submit" class="btn btn-primary" style="border-color:transparent">Delete</button>
            <a asp-controller="MenuMVC" asp-action="Index" class="btn btn-secondary" style="color:#8b4513">Back</a>
        </div>
    </form>
</body>

MVC/Views/MenuMVC/Details.cshtml
@model WebAPI.Models.Menu
@using ProjetoLDS.Models
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0;
        padding: 0;
        text-align: center;
    }

    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 60px;
        line-height: 60px;
        display: flex;
        justify-content: center;
        align-content: end;
    }

    h1 {
        color: #8B4513;
        font-weight: bold;
    }

    .product-container {
        display: flex;
        flex-wrap: wrap;
        gap: 29px;
    }

    .product-card {
        flex: 0 0 calc(33.33% - 20px);
        box-sizing: border-box;
        border: 1px solid #ddd;
        padding: 15px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
    }

        .product-card img {
            max-width: 100%;
            height: auto;
        }

        .product-card h3 {
            margin-top: 10px;
            color: #333;
        }

        .product-card p {
            color: #888;
        }

    .info-box {
        background-color: #ffffff; /* White background */
        border: 1px solid #dddddd; /* Light gray border */
        padding: 10px; /* Padding around the content */
        margin-bottom: 10px; /* Bottom margin for spacing between boxes */
        font-size: 16px; /* Increase font size */
    }
</style>



<h1>Detalhes do Menu</h1>
<body>
    <div class="info-box">
        <div>
            <label for="menuName">
                <span style="color: #8B4513; font-weight: bold">Nome do Menu:</span> @Model.Name
            </label>
        </div>

        <div>
            <label for="menuPrice">
                <span style="color: #8B4513; font-weight: bold">Preço do Menu:</span> @(Model.Preco / 100M)€
            </label>
        </div>

        <div>
            <label for="menuPoints">
                <span style="color: #8B4513; font-weight: bold">Pontos Necessários:</span> @Model.PontosNecessarios
            </label>
        </div>
    </div>

    <div class="product-container">
        @foreach (var item in ViewBag.ItemAtribuido)
        {
            <div class="product-card">
                <!-- Adicione a imagem do item aqui -->
                <img src="~/Images/ItemImages/@item.ImagePath" alt="Imagem do Item" style="width: 200px; height: 200px; object-fit: cover; display: block; margin: 0 auto;">

                <h3>@item.Name</h3>
                <p>@item.Preco</p>
            </div>
        }
    </div>
    <a asp-controller="MenuMVC" asp-action="Index" class="btn btn-secondary" style="color:#8b4513">Back</a>

</body>

MVC/Views/MenuMVC/Edit.cshtml
@model Menu
@using WebAPI.Enums;

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0;
        padding: 0; 
        text-align: center; 
    }

    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 60px; 
        line-height: 60px; 
        display: flex;
        justify-content: center;
        align-content: end;
    }

    h1 {
        color: #8B4513;
        font-weight: bold;
    }

    form {
        background-color: #fcece1; 
        border: none;
    }
</style>


<h1>Edit Menu</h1>
<body>
    <form method="post" asp-controller="MenuMVC" asp-action="Edit" enctype="multipart/form-data">
        <div class="border m-2 p-4">
            <div asp-validation-summary="All"></div>
            <input asp-for="Id" hidden />

            <div class="mb-3">
                <div class="mb-3">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control" required />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Preco" class="form-label"></label>
                    <input asp-for="Preco" class="form-control" />
                    <span asp-validation-for="Preco" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="PontosNecessarios" class="form-label"></label>
                    <input asp-for="PontosNecessarios" class="form-control" />
                    <span asp-validation-for="PontosNecessarios" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Image" class="form-label"></label>
                    <input asp-for="Image" type="file" class="form-control" />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <label>Items</label>
                <div>
                    @{

                    }
                    @foreach (var item in ViewBag.Menu.Items)
                    {
                        bool isChecked = false;
                        foreach (var itemAtribuido in ViewBag.ItemAtribuido)
                        {
                            if (itemAtribuido.IdItem == item.Id)
                            {
                                isChecked = true;
                                break;
                            }
                        }
                        <div class="form-check">
                            <input type="checkbox" id="Check_@item.Id" name="itemsSelecionados" value="@item.Id" checked="@isChecked" />
                            <label for="Check_@item.Id">@item.Name</label>
                        </div>
                    }
                </div>
            </div>
            <button type="submit" class="btn btn-primary" style="border-color:transparent">Update</button>
            <a asp-controller="MenuMVC" asp-action="Index" class="btn btn-secondary" style="color:#8b4513">Back</a>
        </div>
        <input asp-for="Id" hidden />
        <input asp-for="ImagePath" hidden />
    </form>
</body>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

MVC/Views/MenuMVC/Index.cshtml
@* @using WebAPI.Models*@
@model List<Menu>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0;
        padding: 0;
        text-align: center;
    }

    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 60px;
        line-height: 60px;
        display: flex;
        justify-content: center;
        align-content: end;
    }

    h1 {
        color: #8B4513;
        font-weight: bold;
    }

    .product-container {
        display: flex;
        flex-wrap: wrap;
        gap: 29px;
    }

    .product-card {
        flex: 0 0 calc(33.33% - 20px);
        box-sizing: border-box;
        border: 1px solid #ddd;
        padding: 15px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
    }

        .product-card img {
            max-width: 100%;
            height: auto;
        }

        .product-card h3 {
            margin-top: 10px;
            color: #333;
        }

        .product-card p {
            color: #888;
        }
</style>

<h1>Menus</h1>

@if (ViewBag.UserCookieExists == "Administrador")
{
    <div>
        <a asp-controller="MenuMVC" asp-action="Create" class="btn btn-primary">
            Create New Menu
        </a>
    </div>
}

<div class="product-container">
    @foreach (Menu menu in Model)
    {
        <div class="product-card">
            <img src="~/Images/ItemImages/@menu.ImagePath" alt="Imagem do Ingrediente" style="width: 200px; height: 200px; object-fit: cover; display: block; margin: 0 auto;">
            <h3>@menu.Name</h3>
            <p>@(menu.Preco / 100M)€</p>
            <div>
                @if (ViewBag.UserCookieExists == "Administrador")
                {
                    <a asp-controller="MenuMVC" asp-action="Edit" asp-route-id="@menu.Id">Edit</a>
                    <a asp-controller="MenuMVC" asp-action="Delete" asp-route-id="@menu.Id">Delete</a>
                }
                <a asp-controller="MenuMVC" asp-action="Details" asp-route-id="@menu.Id">Ver</a>
            </div>
        </div>
    }
</div>